# Generated by Django 4.0.3 on 2022-03-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('room_type', models.CharField(choices=[('standard', 'standard'), ('deluxe', 'deluxe'), ('double', 'double')], max_length=30)),
                ('price', models.FloatField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
