# Generated by Django 4.0.3 on 2022-03-30 14:05

import bookings.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=bookings.models.one_day_hence)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
