# Generated by Django 4.0.3 on 2022-03-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('bookings', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='bookings.room'),
        ),
    ]
