# Generated by Django 4.0.3 on 2022-03-30 14:27

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_booked_by_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(default=bookings.models.generate_room_code, max_length=10, unique=True),
        ),
    ]
