# Generated by Django 4.0.3 on 2022-03-30 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.customer')),
                ('paid_for', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bookings.booking')),
            ],
        ),
    ]
